version: '3.7'

services:
  nats-playground:
    container_name: nats-playground
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - user_id=$UID
        - group_id=$GID
        - user=$USER
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on: ['n1.example.net']
    links: ['n1.example.net']
    working_dir: /app
    networks: ['nats']
    command: yarn start:debug

  # Run the main NATS JetStream server.
  n1.example.net:
    container_name: n1
    image: synadia/jsm:nightly-20210429
    dns_search: example.net
    entrypoint: /nats-server
    command: --name N1 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://n1:4245,nats://n2:4245,nats://n3:4245 -p 4222
    networks:
      - nats
    ports:
      - 4222:4222
    volumes:
      - ./jetstream-cluster/n1:/data

  # Run the auxiliary NATS JetStream server.
  n2.example.net:
    container_name: n2
    image: synadia/jsm:nightly-20210429
    dns_search: example.net
    entrypoint: /nats-server
    command: --name N2 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://n1:4245,nats://n2:4245,nats://n3:4245 -p 4222
    networks:
      - nats
    ports:
      - 4223:4222
    volumes:
      - ./jetstream-cluster/n2:/data

  # Run the auxiliary NATS JetStream server.
  n3.example.net:
    container_name: n3
    image: synadia/jsm:nightly-20210429
    dns_search: example.net
    entrypoint: /nats-server
    command: --name N3 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://n1:4245,nats://n2:4245,nats://n3:4245 -p 4222
    networks:
      - nats
    ports:
      - 4224:4222
    volumes:
      - ./jetstream-cluster/n3:/data

networks:
  nats:
    name: nats
